### PR TITLE
Remove Stammitsch-filter when adding talks for the time being

### PR DESCRIPTION
**Pull request by cherti**
Currently we don't have Stammtisch, therefore there is no point of not having Talks on that date, hence removing the check for now.

### CODE REVIEW

**Comment by stapelberg** [comment]
Can you add a TODO to re-instate the check later?

**Comment by cherti** [comment]
Right in the source-file?

**Comment by cherti** [comment]
Note is done in the source, commit is amended so it can simply be reverted later.

**Comment by cherti** [comment]
Thx, merged without the git-interface, therefore closing here.

**Pull request closed without merging**
